


#person:
#  lastName: zhangsan
#  age: 18
#  boss: false
#  birth: 2018/11/13
#  map: {k1: v1,k2: v2}
#  list:
#    - basketball
#    - football
#    - baseball
#  dog:
#    name: katun
#    id: 1
server:
  port: 8081
spring:
  profiles:
    active: dev

---
server:
     port: 8083
spring:
  profiles: test

---
server:
  port: 8084
spring:
  profiles: prod